### ISSUE TITLE
Memory leaks in class methods

### ISSUE THREAD

**Issue by ian-z2live** [robb/Underscore.m#11]
The class-level "wrap" methods in your array and dictionary wrappers are leaking memory.
- (USArrayWrapper *)wrap:(NSArray *)array;
  {
  return [[USArrayWrapper alloc] initWithArray:[array copy]];
  }

According to Cocoa conventions, callers are not responsible for releasing an object created with this method, because there is no 'new', 'init' or 'copy' in the method name.  However, you create the object with [[USArrayWrapper alloc] init], which will leave the returned object with a retain count of 1.  If the caller never releases it, it gets leaked.

Furthermore, the call to '[array copy]' is allocating a new instance with a retain count of 1, and this object never gets released.

Now, these issues aren't important if you're using ARC, since the correct releases will be inserted for you, but if that is what you're expecting, your documentation should indicate that the code should only be used in ARC projects.  I suspect that this is the case, because you also didn't implement a dealloc method.

If you plan to support non-ARC usage, change the wrapper's array property to have copy semantics, add a dealloc method and release the array there, and change wrap to look like this:
- (USArrayWrapper *)wrap:(NSArray *)array;
  {
  return [[[USArrayWrapper alloc] initWithArray:array] autorelease];
  }

Apologies if you're already aware of this and chose consciously to only support ARC.

**Comment by robb** [comment]
You are right, this code is only meant to be compiled with ARC.
I'll make this clear in the documentation and see if I can add a compile-time warning if ARC is not enabled.

Thanks!

**Comment by ian-z2live** [comment]
My pleasure.  I like your library a lot!  Nice work!

On Fri, Jun 1, 2012 at 12:49 PM, Robert Böhnke
reply@reply.github.com
wrote:

> You are right, this code is only meant to be compiled with ARC.
> I'll make this clear in the documentation and see if I can add a compile-time warning if ARC is not enabled.
> 
> Thanks!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/robb/Underscore.m/issues/11#issuecomment-6069293

## 

Ian Levin
