### ISSUE TITLE
Add support for NSString?

### ISSUE THREAD

**Issue by robb** [robb/Underscore.m#22]
Just thinking out loud here

``` objective-c
Underscore.string(@"It was the best of times, it was the worst of times")
     .downcase
     .strip(@[ @"," ]) 
     .split(@" ")
     .uniq // Array
     .join(@", ")
     .unwrap; // @"it, was, the, best, of, times, worst"
```

Suppose there was `apply` for dictionaries 

``` objective-c
Underscore.dict(data)
    .filterKeys(Underscore.isKeyPath(target))
    .defaults(kDefaultValues)
    .apply(target)
```

**Comment by robb** [comment]
Or even better

``` Objective-C
NSDictionary *dataFromJSON = @{
    @"created_at": [NSDate …],
    @"username": @"robb",
    @"full_name": @"Robert Böhnke"
};

User *robb = [[User alloc] init];

Underscore.dict(dataFromJSON)
    .mapKeys(Underscore.toCamelCase) // shit, should map for dicts be mapObjects all of a sudden?
    .filterKeys(Underscore.isKeyPath(target))
    .defaults(kUserDefaultValues)
    .apply(robb);
```

**Comment by robb** [comment]
Maybe it would make sense to distribute Underscore.strings as a separate CocoaPod?

**Comment by IvanUshakov** [comment]
I think better use subspecs for this. Documentation can be find in: http://docs.cocoapods.org/specification.html#subspec

**Comment by robb** [comment]
Hmm, so

``` ruby
pod 'Underscore.m'
```

would install Underscore.m + Underscore.strings but

``` ruby
pod 'Underscore.m/Strings'
```

would only install the latter?

That's pretty much the opposite of what I had in mind, the default distribution should only include Underscore.m's data structure related stuff and Underscore.strings would add strings manipulation on top of that.

**Comment by IvanUshakov** [comment]
No,

``` ruby
pod 'Underscore.m'
```

install only Underscore.m but

``` ruby
pod 'Underscore.m'
pod 'Underscore.m/Strings'
```

install both Underscore.m and Underscore.strings

I believe, that's with subspec you can do it. For example, create underscore.strings subspec and core subspec, that don't depend on underscore.strings. But, I can be wrong

**Comment by robb** [comment]
Cool, well I guess I first have to build Underscore.strings :wink:

**Comment by vascoorey** [comment]
@robb I wouldn't mind getting this one started out. Any thoughts on a spec? Was thinking we could look at the ruby strings package.

**Comment by robb** [comment]
Modeling this after Ruby seems reasonable. There is also a [string support library for underscore.js](https://github.com/epeli/underscore.string).

I think good starting points are `trim`, `downcase`, `upcase`, `capitalize`, `split` (returns an array wrapper), `join` (on an array wrapper).

**Comment by robb** [comment]
I'd suggest you start a [WIP] Pull Request as soon as you find time and we move the discussion for the first set of string methods over there?

**Comment by vascoorey** [comment]
Roger that @robb, cheers. One more for the weekend ;)
