### ISSUE TITLE
Add sorting abilities for NSArray

### ISSUE THREAD

**Issue by amiel** [robb/Underscore.m#23]

**Comment by robb** [comment]
``` objective-c
_.array(numbers)
  .filter(_.isNumber)
  .sort(^NSComparisonResult(NSNumber *a, NSNumber *b){
    return [a compare:b];
  })
  .unwrap;
```

**Comment by amiel** [comment]
Is this an indication that the feature already exists? Or a note on what the api should be?

I haven't found `sort` in the codebase, and I like the api, so if you agree with the feature, I'd be happy to implement it...

**Comment by robb** [comment]
yeah, just taking notes here ;)
Is that kind of what you had in mind?

**Comment by robb** [comment]
Maybe add something like

``` objective-c
typedef NSComparisonResult (^UnderscoreSortBlock)(id a, id b);

// ...

@interface Underscore : NSObject
+ (UnderscoreSortBlock(^)(UnderscoreSortBlock))reverse;
@end
```

?

**Comment by amiel** [comment]
> Is that kind of what you had in mind?

Yep, exactly.

If you're not in a hurry, I'm happy to implement it.
