### ISSUE TITLE
Where to import and alias?

### ISSUE THREAD

**Issue by s12chung** [robb/Underscore.m#26]
Hi Robert,

Love the library, as I love underscore.js. Got it working with the CocoaPods installation.

But I gotta ask, how do you install Underscore.m globally with the alias? ie. where do I put:

``` objective-c
#import "Underscore.h"
#define Underscore _
```

I tried <project name>-Prefix.pch, which worked in 0.1.0. It doesn't seem to work now. Instead, I get:
`Pods/Headers/Underscore.m/Underscore.h:34:3: Underscore.m requires Automatic Reference Counting to be enabled`

Thanks!

**Comment by robb** [comment]
Hmm, I do usually put it in the prefix header like you did. Your project is non-ARC, yes?
Is the mixture of ARC and non-ARC code otherwise working?

I'll try to look for more causes, but I'm without a development machine at the moment so it may take me a while.

**Comment by s12chung** [comment]
Thanks for getting back so quickly.

My project is ARC. I do mix some non-ARC code because of some external code (and set compiler flags for those files). The library works file if I import "Underscore.h" into each file I use underscore with.

Sure, thanks again!

**Comment by s12chung** [comment]
if this helps: https://github.com/rs/SDWebImage/issues/229

**Comment by robb** [comment]
So what they are saying is there is nothing you can do and you need to remove Underscore.m from your Prefix Header when mixing ARC and Non-ARC?

**Comment by s12chung** [comment]
Pretty much. I read it over again and figured out their solution.
