### ISSUE TITLE
Possible retain cycle in flatten

### ISSUE THREAD

**Issue by trevorfancher** [robb/Underscore.m#28]
clang is giving me a warning about a possible retain cycle in -flatten on USArrayWrapper.

For now I am surrounding the block definition in

``` c
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Warc-retain-cycles"
//flatten block defined here
#pragma clang diagnostic pop
```

to suppress the warning.

It seems to me that there really is a retain cycle, but I'm not really qualified to say for sure. If there is then it should be fixed.

**Comment by robb** [comment]
Good catch :+1:

**Comment by robb** [comment]
Great to see how Clang is improving, catching these kinds of subtle mistakes :smile_cat:
