### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by tmcnab** [robb/Underscore.m#36]
I hate questions like these, but is this project still being actively maintained?

**Comment by robb** [comment]
Yup, is anything broken for you?

**Comment by robb** [comment]
If you're wondering about the lack of updates, I suppose haven't encountered an actual need for drop, zipWith or support for NSSet or NSString (#29, #12, #10, #22) in any of my apps yet.

That being said, I am thinking about making Underscore.m somewhat of a dynamic wrapper around [Asterism](https://github.com/robb/Asterism) so people can have their choice of (chaining + dynamic inspection) or (typesafety + overloading)

**Comment by tmcnab** [comment]
Ah okay, thanks for that @robb. It was more for the fact I'd hate using a library/framework if it's dead. Great work on Underscore.m!

**Comment by robb** [comment]
:bow:
