### ISSUE TITLE
Cocoapods ARC issue

### ISSUE THREAD

**Issue by rimsan** [robb/Underscore.m#37]
You have the following code in **Underscore.h**:

``` objective-c
#if !__has_feature(objc_arc)
# error Underscore.m requires Automatic Reference Counting to be enabled
#endif
```

As far as Cocoapods creates project with disabled ARC and -fobjc-arc flags for <compiled> sources - project can't be builded.

**Comment by robb** [comment]
Are you saying that an error is raised when Underscore.m is used using Cocoapods in a an non-ARC project?

**Comment by robb** [comment]
Turns out that was fixed in #27 – guess it's time I put a new version on Cocoapods

**Comment by rimsan** [comment]
Yep. And thanks for your great work!

**Comment by robb** [comment]
[I've sumitted Underscore.m 0.2.1](https://github.com/CocoaPods/Specs/commit/31a4c51ff9ab202cc2a248766551a768310e67dd)

:bow:
