### ISSUE TITLE
Why wrappers are required? 

### ISSUE THREAD

**Issue by yuanmai** [robb/Underscore.m#40]
Any reason to prefer wrapper over Category?
Using category, we can achieve:

``` Objective-C
@[a, b, c].map(^(NSString *string) {
    return string.capitalizedString;
})
```

without any wrapping, right?

**Comment by robb** [comment]
whoops, hit reply too early

**Comment by robb** [comment]
Yes, but categories **should** be prefixed, so you'd have

``` objc
@[a, b, c].us_map(^(NSString *string) {
    return string.capitalizedString;
});
```

which I don't find very pleasing, aesthetically. If prefer that, which I totally understand, check out [BlocksKit](https://github.com/pandamonia/BlocksKit/), it uses categories and supports a similar functionality.

That being said, I have [a branch where the wrappers are NSProxies](https://github.com/robb/Underscore.m/tree/0.3.0-development), allowing you to skip the unwrapping, like so:

``` objc
NSArray *myArray = _.wrap(@[foo])
   .map(^(NSString *string) {
        return string.capitalizedString;
    })
    .filter(^(NSString *foo){
        // yadda yadda
    });
```

Note that for the non-chaining use case you can already use

``` objc
_.arrayMap(@[a, b, c], ^(NSString *string) {
    return string.capitalizedString;
});
```

**Comment by yuanmai** [comment]
Thanks for your explanation.
