### ISSUE TITLE
Get NSDictionary from NSArray and vice versa

### ISSUE THREAD

**Issue by rudensm** [robb/Underscore.m#47]
Hi,
For example,

```
NSArray *items = @[@"key1", @"key2", @"key3"];
_.array(items)
.mapDict(^(id obj) {
        return @{obj[@"key1"]: @"some_value"};
    });
.unwrap;
```

as a result we get

```
@{
  @"key1": @"some_value",
  @"key2": @"some_value",
  @"key3": @"some_value",
  }
```

Q: Is there an option to somehow get this with existing methods?

**Comment by ipetkov** [comment]
You could simply map over an array of keys to get a values array and build a dictionary out of both of them:

``` objective-c
NSArray *keys = @[ @"key1", @"key2", @"key3"];
NSArray *values = _.arrayMap(keys, ^id (id key){
    return [@"some-value-for-" stringByAppendingString:key];
});

NSDictionary *dict = [NSDictionary dictionaryWithObjects:values forKeys:keys];
```

Giving the result

``` objective-c
@{
    @"key1": "some-value-for-key1",
    @"key2": "some-value-for-key2",
    @"key3": "some-value-for-key3"
}
```

If you'd like even more power for creating the values array you could use [`zipWith`](https://github.com/robb/Underscore.m/blob/development/Underscore/USArrayWrapper.m#L228) and create a dictionary with the results.

**Comment by rudensm** [comment]
Thx, dude, that's awesome)
