### ISSUE TITLE
Will support groupBy ?

### ISSUE THREAD

**Issue by swordray** [robb/Underscore.m#53]
It is very useful.

http://underscorejs.org/#groupBy

**Comment by vascoorey** [comment]
@robb this sounds like something we could add, no ?

I've made a quick implementation of `groupBy` on `USArrayWrapper` that looks like this:

``` objective-c
- (USDictionaryWrapper *(^)(UnderscoreGroupingBlock))groupBy
{
    return ^USDictionaryWrapper *(UnderscoreGroupingBlock block) {
        NSMutableDictionary *result = [NSMutableDictionary dictionary];

        for(id obj in self.array) {
            id <NSCopying> groupIdentifier = block(obj);
            NSArray *groupContents = result[groupIdentifier] ?: @[];
            groupContents = [groupContents arrayByAddingObject:obj];
            result[groupIdentifier] = groupContents;
        }

        return [USDictionaryWrapper wrap:result];
    };
}
```

While I've used `NSArray` for a naive implementation we could change it to be `NSSet` backed in order to be similar to the Underscore.js implementation

**Comment by robb** [comment]
I feel like `NSArray` is probably easier, tho Asterism uses NSSets fwiw

**Comment by vascoorey** [comment]
Yeah `NSArray` for a first implementation & we can change to `NSSet` if needed.
