### ISSUE TITLE
Published Pod is old

### ISSUE THREAD

**Issue by richardPFisk** [robb/Underscore.m#65]
Thanks for a great library.

Would it be possible to publish an updated version 0.3.0? This would then allow easy use of functions such as `groupBy`. The current version, 0.2.1, does not contain `groupBy`.

Please let me know if I can help.

Thanks again.

**Comment by kvnify** [comment]
Working on it. Hopefully very soon.

**Comment by kvnify** [comment]
0.3.0 has been released.
